# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1acebb64437fcd791c44a193f36b85a652791eb365a85ad94a32125c8aa6d5e0cd76a1c4f18a7b2e3fea62350be78cf28afeb5929b0008356591823c7a4ce4a

test:
  secret_key_base: 8504bf541d3f53f6ec423f7e27541a06922d67e950aaa0c53e0fdff255a19609fc798a3549d53246cd421e705303ba19888b302eb01750ab85e002e377ad8f04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
